models:
  LinearRegression:
    class: "sklearn.linear_model.LinearRegression"
    params: 
  DecisionTreeRegressor:
    class: "sklearn.tree.DecisionTreeRegressor"
    params: 
      max_depth: [3, 5, 7, 9]
      splitter: ["best", "random"]
  RandomForestRegressor:
    class: "sklearn.ensemble.RandomForestRegressor"
    params:
      n_estimators: [10, 50, 100]
      max_depth: ["None", 3, 5, 10]
      min_samples_leaf: [1, 3, 5]
      min_samples_split: [2, 5, 10, 30]  
  GradientBoostingRegressor:
    class: "sklearn.ensemble.GradientBoostingRegressor"
    params:
      n_estimators: [10, 50, 100]
      max_depth: [3, 5, 10]
      min_samples_leaf: [1, 3, 5]
      min_samples_split: [2, 5, 10, 30]
      learning_rate: [0.01, 0.05, 0.1]
    

